name: Acceptance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: terraformtesting/acceptance-tests@v2.1.0
        with:
          TG_LOG: INFO
          RUN_ALL: true
